# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2015-12-23 00:53
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('minglu', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='gssldata',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('zch', models.TextField()),
                ('qiyename', models.TextField()),
                ('hzriqi', models.TextField()),
                ('djjg', models.TextField()),
            ],
            options={
                'ordering': ['-hzriqi'],
                'db_table': 'gsqiyesheli',
            },
        ),
        migrations.CreateModel(
            name='gszxdata',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('zch', models.TextField()),
                ('qiyename', models.TextField()),
                ('hzriqi', models.TextField()),
                ('djjg', models.TextField()),
            ],
            options={
                'ordering': ['-hzriqi'],
                'db_table': 'gsqiyezhuxiao',
            },
        ),
        migrations.CreateModel(
            name='ssdata',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('zch', models.TextField()),
                ('mcyename', models.TextField()),
                ('fddbri', models.TextField()),
                ('zyxmlb', models.TextField()),
                ('dz', models.TextField()),
                ('rjzczb', models.TextField()),
                ('qylx', models.TextField()),
                ('clrq', models.TextField()),
                ('yyqx', models.TextField()),
                ('hzrq', models.TextField()),
                ('djjg', models.TextField()),
                ('zt', models.TextField()),
                ('jyfw', models.TextField()),
                ('xydm', models.TextField()),
            ],
            options={
                'ordering': ['-hzrq'],
                'db_table': 'ssjibenxinxi',
            },
        ),
        migrations.DeleteModel(
            name='ssjibenxinxi2',
        ),
    ]
