#coding=utf8
"""
Django settings for mingluku project.

Generated by 'django-admin startproject' using Django 1.8.1.

For more information on this file, see
https://docs.djangoproject.com/en/1.8/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/1.8/ref/settings/
"""

# Build paths inside the project like this: os.path.join(BASE_DIR, ...)
import os
import socket

BASE_DIR = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/1.8/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = 'xr2(ho#3-)6(te_+%6h!)eogr6-%wyj$&cl$5vd39v%7te1^ji'

# SECURITY WARNING: don't run with debug turned on in production!

#用于调试用
DEBUG = True
#TEMPLATE_DEBUG = DEBUG

#在我的本机上跑就开启调试否则就不开启调试
if socket.gethostname() == 'DESKTOP-H7AJCFN':
    #DEBUG = TEMPLATE_DEBUG = True
    DEBUG = True
else:
    #DEBUG = TEMPLATE_DEBUG = False
    DEBUG =  False

ALLOWED_HOSTS = []
#ALLOWED_HOSTS = ['127.0.0.1', 'localhost']


# Application definition

INSTALLED_APPS = (
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    'minglu',
    #'pagination',
 

    #'xadmin', # 添加该行
)

MIDDLEWARE_CLASSES = (
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.auth.middleware.SessionAuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
    'django.middleware.security.SecurityMiddleware',
    #'django.middleware.csrf.CsrfResponseMiddleware',
)

ROOT_URLCONF = 'mingluku.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [],
        'APP_DIRS': True,
        'OPTIONS': {
            'TEMPLATE_DEBUG' : DEBUG,        
            #'debug': DEBUG,
            'context_processors': [
                'django.template.context_processors.debug',
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]

WSGI_APPLICATION = 'mingluku.wsgi.application'


# Database
# https://docs.djangoproject.com/en/1.8/ref/settings/#databases

DATABASES = {
    'default': {
        #'ENGINE': 'django.db.backends.sqlite3',
        #'NAME': os.path.join(BASE_DIR, 'db.sqlite3'),
        'ENGINE': 'django.db.backends.mysql',
        'NAME': 'danweimingluku',
        #'USER': 'root', 
        #'PASSWORD': '' ,
        #'HOST':'localhost',
        'PASSWORD': 'mysqlpwd',
        'USER': 'mysql',
        'HOST':'10.43.18.42',
        'PORT': '3306',
    }
}


# Internationalization
# https://docs.djangoproject.com/en/1.8/topics/i18n/

LANGUAGE_CODE = 'en-us'

TIME_ZONE = 'UTC'

USE_I18N = True

USE_L10N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/1.8/howto/static-files/

STATIC_URL = '/static/'

#STATIC_PATH = os.path.join(BASE_DIR, 'templates/static').replace('\\','/')

STATIC_PATH ='./static/'

ROOT_PATH=''

STATIC_ROOT = ''
#STATIC_ROOT = os.path.join(os.path.dirname(__file__),'static')

STATICFILES_DIRS = (
    #os.path.join(ROOT_PATH,'static'),
    os.path.join(STATIC_ROOT, "static"),  
)

